#!/usr/bin/env node
/**
 * End-to-end test for theme generation
 * Creates minimal test data and generates a theme
 */

import { mkdirSync, writeFileSync, existsSync, rmSync } from 'fs';
import { join } from 'path';
import { Logger, LogLevel } from '../crawler/src/lib/logger.js';
import { runGenerator } from '../theme-generator/src/generator/runner.js';

const TEST_DIR = join(process.cwd(), 'test-e2e-output');
const INPUT_DIR = join(TEST_DIR, 'input');
const OUTPUT_DIR = join(TEST_DIR, 'output');

async function main() {
  const logger = new Logger(LogLevel.INFO);

  try {
    logger.info('=== E2E Theme Generation Test ===');

    // Clean up previous test
    if (existsSync(TEST_DIR)) {
      rmSync(TEST_DIR, { recursive: true, force: true });
    }

    // Create test structure
    logger.info('Creating test data...');
    mkdirSync(INPUT_DIR, { recursive: true });
    mkdirSync(join(INPUT_DIR, 'spec'), { recursive: true });
    mkdirSync(join(INPUT_DIR, 'pages', 'home', 'spec'), { recursive: true });
    mkdirSync(join(INPUT_DIR, 'assets'), { recursive: true });

    // Create manifest.json
    const manifest = {
      baseUrl: 'https://example.com',
      pages: [{ url: 'https://example.com/', path: '/' }],
    };
    writeFileSync(join(INPUT_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2));

    // Create design-tokens.json
    const designTokens = {
      colors: {
        primary: '#0073aa',
        secondary: '#23282d',
      },
      typography: {
        fontFamilies: ['Arial, sans-serif'],
      },
    };
    writeFileSync(
      join(INPUT_DIR, 'spec', 'design-tokens.json'),
      JSON.stringify(designTokens, null, 2)
    );

    // Create layout-patterns.json
    const layoutPatterns = {
      patterns: [],
    };
    writeFileSync(
      join(INPUT_DIR, 'spec', 'layout-patterns.json'),
      JSON.stringify(layoutPatterns, null, 2)
    );

    // Create pagespec.json for home
    const pageSpec = {
      slug: 'home',
      url: 'https://example.com/',
      sections: [
        {
          id: 'hero-1',
          type: 'hero',
          heading: 'Welcome to Our Site',
          textBlocks: ['This is a test page generated by the theme generator.'],
          ctas: [{ text: 'Learn More', href: '#learn-more' }],
          media: [],
        },
      ],
    };
    writeFileSync(
      join(INPUT_DIR, 'pages', 'home', 'spec', 'pagespec.json'),
      JSON.stringify(pageSpec, null, 2)
    );

    logger.info('Test data created');

    // Run theme generation
    logger.info('Running theme generator...');
    await runGenerator(
      {
        baseUrl: 'https://example.com',
        inDir: INPUT_DIR,
        outDir: OUTPUT_DIR,
        themeName: 'e2e-test-theme',
        mode: 'hybrid',
        emitPatterns: true,
        emitThemeJson: true,
      },
      logger
    );

    logger.info('');
    logger.info('✅ E2E Test completed successfully!');
    logger.info(`Generated theme at: ${join(OUTPUT_DIR, 'e2e-test-theme')}`);
    logger.info('');
    logger.info('Next steps:');
    logger.info('1. Inspect the generated theme files');
    logger.info('2. Copy to WordPress themes directory');
    logger.info('3. Activate in WordPress admin');
    process.exit(0);
  } catch (error) {
    logger.error(`E2E Test failed: ${(error as Error).message}`);
    console.error(error);
    process.exit(1);
  }
}

main();
